---
# Setup apache with ssl


- name: Install httpd and unzip
  yum: 
    name:
      - httpd
      - unzip
    state: present

- name: Create Wordpress directory
  file:
    path: "{{ wordpress_directory }}"
    owner: "{{ remote_deploy_user }}"
    group: "{{ remote_deploy_group }}"
    mode: 0755
    state: directory

- name: Install httpd.conf
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify: restart httpd

- name: Install wordpress.conf
  template:
    src: wordpress.conf.j2
    dest: /etc/httpd/conf.d/wordpress.conf
  notify: restart httpd

- name: Move conf.d files
  copy: 
    src: "{{ role_path }}/files/httpd/conf.d/"
    dest: /etc/httpd/conf.d/
  notify: restart httpd

- name: http service state
  service: 
    name: httpd 
    state: started 
    enabled: yes
