# You'll need to download and source your credentials before this will work:
#  https://research.csc.fi/pouta-credentials
#

- name: Create virtual machine on cPouta
  hosts: localhost # The OpenStack Shade modules run by Shade on your local machine.
  remote_user: almalinux
  become: false

  vars:
  roles:
    - role: kielipankki.common.create_instances
      tags: create_instances

- name: Install Portal
  hosts: portal
  become: yes  # sudo to root

  roles:
      - role: kielipankki.common.backup
        tags: backup
      - role: kielipankki.common.postfix
        tags: postfix
      - role: kielipankki.common.opsview
        tags: opsview
      - role: mariadb
        tags: mariadb
      - role: apache
        tags: apache
      - role: php
        tags: php
      - role: wordpress
        tags: wordpress
      - role: firewall
        tags: firewall
      - role: pid_generator
        tags: pid_generator

