---
- name: Install Epel first
  package:
    name: epel-release
    state: present

# at present we need one key
- name: Import Remi GPG keys
  rpm_key:
    state: present
    key: "{{ item }}"
  loop:
   - https://rpms.remirepo.net/RPM-GPG-KEY-remi2021

- name: Install Remi's RPM repository
  package:
    name: "http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present
    
- name: Enable PHP module
  dnf:
    name: "@php:remi-8.3"
    state: present

- name: Install php and its friends
  package:
    name:
      - php
      - php-fpm
      - php-cli
      - php-mysqlnd
      - php-gd
      - php-mbstring
      - php-xml
      - php-json
      - php-pecl-memcached
      - php-pecl-imagick
      - php-pecl-zip
      - php-intl
    state: present

